---
title: "Influenza A H7N9 in China, 2013"
format: dashboard
theme: "lux"
---

```{r}
# Load packages 
if(!require(pacman)) install.packages("pacman")
pacman::p_load(tidyverse, outbreaks, bslib, bsicons, shiny, 
               rgeoboundaries, plotly, htmltools, reactable)

# dataset
fluH7N9_china_2013 <- outbreaks::fluH7N9_china_2013
```

```{r}
# values for value boxes
total_cases <- as.numeric(nrow(fluH7N9_china_2013))

total_hospitalizations <- nrow(fluH7N9_china_2013 %>% 
  filter(!is.na(date_of_hospitalisation)))

total_deaths <- nrow(fluH7N9_china_2013 %>% 
  filter(outcome == "Death"))
```

```{r}
# col_plot
cases_per_province <- fluH7N9_china_2013 %>%
  group_by(province) %>%
  summarise(number_of_cases = n())

plot_by_province <- cases_per_province %>%
  mutate(tooltip_label = paste(province, number_of_cases, sep = ": ")) %>%
  ggplot(aes(y = reorder(province, number_of_cases), 
             x = number_of_cases,
             text = tooltip_label)) +
  geom_col(fill = "steelblue") +
  labs(x = "Number of Cases", y = NULL) +  
  theme_minimal() + 
  theme(axis.title.y = element_blank(),  
        axis.text.y = element_text(size = 9), 
        axis.text.x = element_text(size = 9), 
        panel.grid.minor = element_blank(),  
        panel.grid.major.x = element_line(color = "gray90"))

# Convert to an interactive plotly plot
cases_province_ggplotly <- ggplotly(plot_by_province, tooltip = "text")
```

```{r results='hide', message=FALSE, warning = FALSE}
pacman::p_load(outbreaks, rgeoboundaries, plotly)

### MAP OF CASES PER PROVINCE
province_summary <- fluH7N9_china_2013 %>% 
  group_by(province) %>% 
  summarise(total_cases = n()) 

china_map <- rgeoboundaries::gb_adm1("china")

# Check the keys to see if join will be successful
setdiff(province_summary$province, china_map$shapeName)
setdiff(china_map$shapeName, province_summary$province)
# Some work to be done to harmonize these

china_map <- china_map %>%
  # Remove the strings Province, Municipality and Autonomous Region 
  # to allow matching
  mutate(province = str_trim(
    str_remove(shapeName, "Province|Municipality|Autonomous Region")
  ))

# Check if join will work fine
setdiff(province_summary$province, china_map$province)

# Fix Guangdong, which based on a quick Google is actually Guangzhou
china_map <- china_map %>% 
  mutate(province = if_else(province == "Guangzhou", "Guangdong", province)) 
  
# Check again
setdiff(province_summary$province, china_map$province)

# Now join
china_map_joined <- 
  left_join(china_map, province_summary, by = "province") %>% 
  # Create tooltip label 
  mutate(tooltip_label = paste0(province, ": ", total_cases))

china_map_plot <- ggplot(china_map_joined) +
  geom_sf(aes(fill = total_cases, text = tooltip_label)) + 
  theme_void() +
  labs(fill = "Number of Cases") + 
  theme(legend.position = "none")

china_map_plot_ggplotly <- 
  ggplotly(china_map_plot, tooltip = "text")
```


# HOME

## Row 1 {height=20%}

```{r}
value_box(
  title = "Total Cases",
  value = total_cases,
  showcase = bsicons::bs_icon("virus"),
  theme = value_box_theme(bg = "#4c96cf"))
```

```{r}
value_box(
  title = "Total Hospitalizations",
  value = total_hospitalizations,
  showcase = bsicons::bs_icon("hospital"),
  theme = value_box_theme(bg = "#153f69"))
```

```{r}
value_box(
  title = "Total Deaths",
  value = total_deaths,
  showcase = bsicons::bs_icon("file-medical"),
  theme = value_box_theme(bg = "#3b6ea1"))
```

## Row 2 {height=80%}

### Col 2.1 {width=35%}

```{r title = "Number of Cases by Province"}
cases_province_ggplotly
```

### Col 2.2 {width=65%}

```{r title = "Map of Provinces by Number of Cases"}
china_map_plot_ggplotly
```

# DOWNLOAD DATA

```{r}
# Load packages 
if(!require(pacman)) install.packages("pacman")
pacman::p_load(htmltools, reactable)

htmltools::browsable(
  tagList(
    reactable(fluH7N9_china_2013, 
              elementId = "fluH7N9_china_2013", 
              searchable = T, 
              filterable = T), 
    
tags$button("Download as CSV", 
            onclick = "Reactable.downloadDataCSV('fluH7N9_china_2013')")
  )
)
```